// This file contains the category data used in the CategorySelector component
// Moving it outside the component prevents it from being recreated on every render

export const categories = [
  {
    id: "homeLawnLabor",
    title: "Home, Lawn, and Manual Labor",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/housebuilding-2Ee0Pra1CpA9xBNHU4c5g7qucnBqHE.png", // housebuilding.png
    subcategories: [
      {
        id: "lawn",
        title: "Lawn, Garden and Snow Removal",
        subcategories: [
          "Lawn & Landscaping",
          "Lawn Treatment",
          "Landscape Lighting",
          "Lawn Mower and Lawn Equipment and Snow Removal Equipment Repair",
          "Tree Service",
          "Plant Nurseries",
          "Mulch Delivery",
          "Soil Tilling",
          "Leaf Removal",
          "Hardscaping",
          "Snow Removal",
          "Other Lawn, Garden and Snow Removal",
        ],
      },
      {
        id: "outside",
        title: "Outside Home Maintenance and Repair",
        subcategories: [
          "Roofing",
          "Masonry Stone and Brick",
          "Glass Block",
          "Siding",
          "Deck Cleaning/Refinishing",
          "Garage Doors",
          "House Painting",
          "Pressure Washing",
          "Foundation Repair",
          "Gutter Cleaning/Repair",
          "Septic Tank Service",
          "Well & Water Pump Repair",
          "Other Outside Home Maintenance and Repair",
        ],
      },
      {
        id: "outdoorStructures",
        title: "Outdoor Structure Assembly/Construction and Fencing",
        subcategories: [
          "Deck/Patio/Porch Construction",
          "Patio and Patio Enclosures",
          "Exterior Cooking Areas",
          "Awnings/Canopies",
          "Playground Equipment Installation/Basketball Hoops",
          "Fountains and Waterscaping",
          "Pond Construction",
          "Solar Panel Installation",
          "Power Generator Installation",
          "Driveway Gate Installation",
          "Earthquake Retrofitting",
          "Mailbox Installation/Repair",
          "Fences",
          "Other Outdoor Structure Assembly/Construction and Fencing",
        ],
      },
      {
        id: "poolServices",
        title: "Pool Services",
        subcategories: [
          "Swimming Pool Installers/Builders",
          "Swimming Pool Maintenance/Cleaning",
          "Other Pool Services",
        ],
      },
      {
        id: "asphaltConcrete",
        title: "Asphalt, Concrete, Stone and Gravel",
        subcategories: [
          "Concrete Driveways",
          "Asphalt Driveways",
          "Other Driveways",
          "Stone & Gravel",
          "Stamped Concrete",
          "Concrete Repair",
          "Other Asphalt, Concrete, Stone and Gravel",
        ],
      },
      {
        id: "construction",
        title: "Home Construction and Design",
        subcategories: [
          "General Contractors",
          "Architect",
          "Home Remodeling",
          "Demolition",
          "Excavating/Earth Moving",
          "Land Surveyors",
          "Other Home Construction and Design",
        ],
      },
      {
        id: "insideHome",
        title: "Inside Home Maintenance and Repair",
        subcategories: [
          "Electricians",
          "Plumbers",
          "Heating, Ventilation, and Air Conditioning Services",
          "Appliance Repair and Installation",
          "Indoor Painting",
          "Drywalling and Repair",
          "Marble & Granite",
          "Water Softeners",
          "Water Heaters",
          "Insulation",
          "Air Duct Cleaning",
          "Dryer Duct Cleaning",
          "Central Vacuum Cleaning",
          "Mold Removal",
          "Plaster Work",
          "Water Damage Repair",
          "Basement Waterproofing",
          "Wallpaper Hanging and Removing",
          "Countertop Installation",
          "Ceiling Fan Installation",
          "Bathtub Refinishing",
          "Cabinet Resurfacing",
          "Cabinet Makers",
          "Tile Installation",
          "Other Inside Home Maintenance and Repair",
        ],
      },
      {
        id: "windowsDoors",
        title: "Windows and Doors",
        subcategories: [
          "Window Replacement",
          "Door Installation",
          "Window Security Film",
          "Window Tinting",
          "Window Dressing/Curtains",
          "Blind/Drapery Cleaning",
          "Locksmith",
          "Other Windows and Doors",
        ],
      },
      {
        id: "floorCarpet",
        title: "Floor/Carpet Care and Installation",
        subcategories: [
          "Carpet Installation",
          "Hardwood Floor Installation",
          "Epoxy Flooring",
          "Tile Flooring",
          "Laminate Flooring",
          "Carpet Cleaning",
          "Floor Buffing and Cleaning",
          "Oriental Rug Cleaning",
          "Other Floor/Carpet Care and Installation",
        ],
      },
      {
        id: "audioVisualSecurity",
        title: "Audio/Visual and Home Security",
        subcategories: [
          "Smart Home Setup",
          "Home Security Solutions",
          "Cinema Room Setup",
          "Telecommunication",
          "Cable/Satellite/Antenna Television",
          "Computer Repair",
          "Other Audio/Visual and Home Security",
        ],
      },
      {
        id: "homeHazard",
        title: "Home Hazard Mitigation",
        subcategories: [
          "Lead-Based Paint Abatement",
          "Radon Mitigation",
          "Mold Removal",
          "Asbestos Removal",
          "Smoke/Carbon Monoxide Detector Installation",
          "Fire Extinguisher Maintenance",
          "Other Home Hazard Mitigation",
        ],
      },
      {
        id: "pestControl",
        title: "Pest Control/ Wildlife Removal",
        subcategories: [
          "Rodent/ Small Animal Infestations",
          "Wildlife Removal",
          "Insect and Bug Control",
          "Other Pest Control/ Wildlife Removal",
        ],
      },
      {
        id: "trashCleanup",
        title: "Trash Cleanup and Removal",
        subcategories: [
          "Biohazard Cleanup",
          "Dumpster Rental",
          "Hauling/Old Furniture and Appliance Removal",
          "Document Shredding",
          "Trash/Junk Removal",
          "Other Trash Cleanup and Removal",
        ],
      },
      {
        id: "homeCleaning",
        title: "Home and Office Cleaning",
        subcategories: [
          "House Cleaning",
          "Office Cleaning",
          "Window Cleaning",
          "Deep Carpet and Floor Cleaning",
          "Other Home and Office Cleaning",
        ],
      },
      {
        id: "fireplacesChimneys",
        title: "Fireplaces and Chimneys",
        subcategories: [
          "Chimney Sweep",
          "Chimney and Chimney Cap Repair",
          "Gas Fireplace Repair",
          "Fireplace Services",
          "Firewood Suppliers",
          "Heating Oil Suppliers",
          "Other Fireplaces and Chimneys",
        ],
      },
      {
        id: "movers",
        title: "Movers/Moving Trucks",
        subcategories: ["Moving Truck Rental", "Piano Movers", "Movers", "Other Movers/Moving Trucks"],
      },
      {
        id: "handymen",
        title: "Handymen",
        subcategories: ["Odd Jobs and Repairs", "Product Assembly", "Other Handymen"],
      },
    ],
  },
  {
    id: "retailStores",
    title: "Retail Stores",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/retail02-PWtKtPOE0qcIIeje2E6crDrL529eTV.png", // retail02.png
    subcategories: [
      "Supermarkets/ Grocery Stores",
      "Department Store",
      "Convenience Store",
      "Clothing Boutique",
      "Discount Store",
      "Warehouse Store",
      "Electronics Store",
      "Bookstore",
      "Jewelry Store",
      "Toy Store",
      "Sporting Goods Store",
      "Furniture Store",
      "Pet Store",
      "Shoe Store",
      "Hardware Store",
      "Stationery Store",
      "Auto Parts Store",
      "Health Food Store",
      "Wine Shop/ Alcohol Sales",
      "Antique Shop",
      "Music Store",
      "Lingerie Store",
      "Gift Shop",
      "Butcher Store",
      "Candy Shop",
      "Mobile Phone Store",
      "Optical Store / Eyewear Boutique",
      "Pharmacy",
      "Home Decor Store",
      "Party Supply Store",
      "Garden Center",
      "Maternity Store",
      "Cosmetics Store",
      "Bicycle Shop",
      "Home Appliance Store",
      "Cheese Shop",
      "Craft Store",
      "Thrift Store",
      "Handbags Store",
      "Baby Store",
      "Tobacco Shop",
      "Art Supply Store",
    ],
  },
  {
    id: "travelVacation",
    title: "Travel and Vacation",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/travel-cRSfCiJRrv8nJvyCPyYr5XlEKRKrY4.png", // travel.png
    subcategories: [
      "Tour and Travel Guides",
      "Travel Agents",
      "Car Rental",
      "Boat Rental",
      "RV Rental",
      "Airpot Pick-up and Drop-off Services",
      "Hotels, Motels, and Resorts",
      "Bed and Breakfast",
      "Air BnB",
      "Camp Grounds and Cabins",
    ],
  },
  {
    id: "tailors",
    title: "Tailors, Dressmakers, and Fabric and Clothes Cleaning and Repair",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Tailor-Ll57NPmzPURm0U8kNHxZEYqs8dPD0Y.png", // Tailor.png
    subcategories: [
      "Tailors, Dressmakers, and Custom Sewers",
      "Laundry and Dry-Cleaning",
      "Shoe and Leather Repair",
      "Costume Makers",
      "Upholsterers",
      "Curtains, Drapes and Window Covering Makers",
    ],
  },
  {
    id: "artDesignEntertainment",
    title: "Art, Design and Entertainment",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/fineArt-g1djwriCCMnMFKsZHa0GREE7PU4be1.png", // fineArt.png
    subcategories: [
      "Fine Artists, Including Painters, Sculptors, and Illustrators",
      "Craft Artists",
      "Musicians and Singers",
      "Recording Studios",
      "Art Galleries",
      "Concert Venues",
      "Fashion Designers",
      "Interior Designers",
      "Photographers and Videographers",
      "Floral Designers",
      "Graphic Designers",
      "All Entertainers and Talent",
      "Talent Agent",
      "Modals",
    ],
  },
  {
    id: "physicalRehabilitation",
    title: "Physical Rehabilitation",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/physicalRehab-OP1TJbwVlpfhhevnkYpk6ZQqMVP2rd.png", // physicalRehab.png
    subcategories: [
      "Occupational Therapists",
      "Physical Therapists",
      "Recreational Therapists",
      "Respiratory Therapists",
      "Speech-Language Pathologists",
      "Exercise Physiologists",
      "Massage Therapist",
      "Art Therapists",
      "Music Therapists",
      "Therapists, All Other",
    ],
  },
  {
    id: "financeInsurance",
    title: "Insurance, Finance, Debt and Sales",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/finance-fqVQ0TmI2kFehcFP7kIOji08oIBhqX.png", // finance.png
    subcategories: [
      "Accountants",
      "Insurance",
      "Advertising",
      "Marketing",
      "Financial and Investment Advisers",
      "Debt Consolidators",
      "Cryptocurrency",
    ],
  },
  {
    id: "weddingsEvents",
    title: "Weddings and Special Events",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/wedding-events-MgUtHJRBQ04ooMmbX5ZuIq4L9m2KqI.png", // wedding-events.png
    subcategories: [
      "Event Halls",
      "Tent and Chair Rentals",
      "Wedding Planners",
      "Food Caterers",
      "Bartenders",
      "Live Music Entertainment",
      "DJs",
      "Performers",
      "Tuxedo Rentals",
      "Limousine Services",
      "Tailors and Seamstresses",
      "Wedding Dresses",
      "Wedding Photographers",
      "Florists",
      "Wedding Cakes",
      "Marriage Officiants",
      "Other Weddings and Special Events",
    ],
  },
  {
    id: "petCare",
    title: "Pet Care",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/cat%20and%20dog-UHW1HU5Xs0PMdXJLC66zBYViQu0jx9.png", // cat and dog.png
    subcategories: [
      "Veterinarians",
      "Pet Hospitals",
      "Dog Fencing/Invisiable Fence",
      "Pet Groomers",
      "Pet Trainers",
      "Pet Walkers",
      "Pet Sitters",
      "Pet Boarders",
      "Pet Breeders",
      "Pet Shops",
      "Pet Rescues",
      "Aquariums/Pet Enclosures",
      "Pet Poop Pickup",
      "Other Pet Care",
    ],
  },
  {
    id: "languageTutoring",
    title: "Language Lessons/School Subject Tutoring",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tutoring-lks6Tjoe1sJjtXJ7OdS2uje11BUiIL.png", // tutoring.png
    subcategories: [
      "Spanish",
      "French",
      "Chinese",
      "American Sign Language",
      "English as a Second Language",
      "Other Language",
      "Math - Elementary",
      "Math - High School",
      "Reading Tutors (Adult and Childeren)",
      "Test Prep",
      "Other Subjects",
    ],
  },
  {
    id: "realestate",
    title: "Home Buying and Selling",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/realitor003-xqIaDhmbEuAgatSXkskyV0Ulolsmr5.png", // realitor003.png
    subcategories: [
      "Real Estate Agent",
      "Real Estate Appraising",
      "Home Staging",
      "Home Inspection",
      "Home Energy Audit",
      "Other Home Buying and Selling",
    ],
  },
  {
    id: "athletics",
    title: "Athletics, Personal Trainers, Group Fitness Classes and Dance Instruction",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/baseball-aixRgKdF2ejVmCFWkhcEu2wlT9pXor.png", // baseball.png
    subcategories: [
      "Baseball/Softball",
      "Golf",
      "Tennis",
      "Basketball",
      "Football",
      "Soccer",
      "Ice Skating",
      "Gymnastics",
      "Pickleball",
      "Table Tennis",
      "Dance",
      "Personal Trainers",
      "Group Fitness Classes",
      "Other Athletics, Personal Trainers, etc",
      "Coaches, Scouts, Umpires, Referees",
      "Swim Instruction",
    ],
  },
  {
    id: "music",
    title: "Music",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/music%20lesson-I1NMnc8dVkG1C6rIOTc5mSghexlmxd.png", // music lesson.png
    subcategories: [
      "Piano Lessons",
      "Guitar Lessons",
      "Violin Lessons",
      "Cello Lessons",
      "Trumpet Lessons",
      "Other Instrument Lessons",
      "Instrument Repair",
      "Used and New Instruments for Sale",
      "Other Music",
    ],
  },
  {
    id: "homecare",
    title: "Home Care",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/home%20health-TftlLaWe43Ltg5qYUWgJyVrfgSfMNd.png", // home health.png
    subcategories: [
      "Non-Medical Elder Care",
      "Non-Medical Special Needs Adult Care",
      "Babysitting (18+ Sitters only)",
      "Other Home Care",
      "Childcare Centers",
      "Adult Day Services",
      "Rehab/Nursing/Respite and Memory Care",
    ],
  },
  {
    id: "automotive",
    title: "Automotive/Motorcycle/RV, etc",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/automech-7SsSfk6EEbz85wtCrG6GZJLEEut0xJ.png", // automech.png
    subcategories: [
      "General Auto Repair",
      "Engine and Transmission",
      "Body Shop",
      "Tire and Brakes",
      "Mufflers",
      "Oil Change",
      "Windshield Repair",
      "Custom Paint",
      "Detailing Services",
      "Car Wash",
      "Auto Parts",
      "ATV/Motorcycle Repair",
      "Utility Vehicle Repair",
      "RV Maintenance and Repair",
      "Other Automotive/Motorcycle/RV, etc",
      "Automotive Sales",
      "Motor Sport/Utility Vehicle/RV Sales",
    ],
  },
  {
    id: "beauty",
    title: "Hair care, Beauty, Tattoo and Piercing",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/haircutting-m6QfXr3W3dUfuj4MZFT90WMNtjed8T.png", // haircutting.png
    subcategories: [
      "Barbers",
      "Hairdressers, Hairstylists, and Cosmetologists",
      "Manicurists and Pedicurists",
      "Skincare Specialists",
      "Hair Removal",
      "Body Sculpting",
      "Spas",
      "Tanning",
      "Tattoo and Scar Removal Services",
      "Hair Wigs and Weaves",
      "Beauty Products",
      "Miscellaneous Personal Appearance Workers",
    ],
  },
  {
    id: "medical",
    title: "Medical Practitioners - non MD/DO",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/doctor-3jjcpWmjxqxLZELTMa9v1TaR1U9TgB.png", // doctor.png
    subcategories: [
      "Chiropractors",
      "Dentists",
      "Orthodontists",
      "Optometrists",
      "Podiatrists",
      "Audiologists",
      "Dietitians and Nutritionists",
      "Naturopaths",
      "Herbalists",
      "Acupuncturist",
      "Orthotists and Prosthetists",
      "Midwives and Doulas",
    ],
  },
  {
    id: "counseling",
    title: "Counselors, Psychologists, Addiction Specialists, Team Building",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/couseling-NTdbl5SQdjHcW9cZCMlFgPSgMin6Ue.png", // couseling.png
    subcategories: [
      "Counselors",
      "Clinical and Counseling Psychologists",
      "Addiction Specialists",
      "Suboxone, Methadone Clinics",
      "Team Building",
      "Industrial-Organizational Psychologists",
      "Motivational Speakers",
    ],
  },
  {
    id: "computers",
    title: "Computers and the Web",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/computer-lox6P5znlsextHA6c7vUkXZNkr2d3q.png", // computer.png
    subcategories: [
      "Computer Network Specialists",
      "Database Administrators",
      "Database Architects",
      "Computer Programmers",
      "Software Developers",
      "Website Developers",
      "Computer Security",
      "BlockChain and Crypto",
      "Technology Consultants",
    ],
  },
  {
    id: "restaurant",
    title: "Restaurant, Food and Drink",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/food%20service-DMhVnw8lOLmeSJkRwocWVAaupQmOgz.png", // food service.png
    subcategories: [
      "Asian",
      "Indian",
      "Middle Eastern",
      "Mexican",
      "Italian",
      "American",
      "Greek",
      "Other Ethnic Foods",
      "Upscale",
      "Casual",
      "Coffee and Tea Shops",
      "Ice Cream, Confectionery and Cakes",
      "Pizzeria",
      "Bars/Pubs/Taverns",
      "Organic/Vegan/Vegetarian/Farm to table",
      "Fast Food",
      "Catering",
      "Buffet",
      "Bakery/Bagels/Donuts",
      "Breakfast",
      "24 hour/Open Late",
      "Carts/Stands/Trucks",
      "Dinner Theater",
      "Sandwich Shops",
      "Drive-Ins",
      "Seafood",
      "Steak House",
      "Sushi",
      "Cafeteria",
    ],
  },
  {
    id: "personalAssistant",
    title: "Assistants",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/assistant-i6Erbhskr6ObActF7XMV9fJslboNmi.png", // assistant.png
    subcategories: [
      "Personal Drivers",
      "Personal Assistants",
      "Companions",
      "Personal Secretaries",
      "Personal Shoppers",
    ],
  },
  {
    id: "mortuaryServices",
    title: "Mortuary Services",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/funeral-TnpegJLL7ue38d0l8qq9dF7O4Q8ND9.png", // Updated to the new funeral director image
    subcategories: ["Funeral Homes", "Cemetaries", "Florists", "Headstones/ Monuments", "Caskets and Urns"],
  },
  {
    id: "lawyers",
    title: "Lawyers",
    image: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/lawyer-DoIQHo7vo03r1owabcFTTLMXiPZ91v.png", // lawyer001.png
    subcategories: [
      "Family Lawyer",
      "Criminal Defense Lawyer",
      "Personal Injury Lawyer",
      "Corporate Lawyer",
      "Immigration Lawyer",
      "Intellectual Property Lawyer",
      "Estate Planning Lawyer",
      "Bankruptcy Lawyer",
      "Civil Litigation Lawyer",
      "Real Estate Lawyer",
      "Entertainment Lawyer",
      "Tax Lawyer",
      "Employment Lawyer",
      "Social Security Disability Lawyer",
      "Workers' Compensation Lawyer",
    ],
  },
]

// Add the missing export
export const categoryData = categories

// Helper function to flatten nested subcategories for search
export const flattenSubcategories = (category: any) => {
  const result: string[] = []

  if (Array.isArray(category.subcategories)) {
    category.subcategories.forEach((sub: any) => {
      if (typeof sub === "string") {
        result.push(sub)
      } else if (typeof sub === "object" && sub.title && Array.isArray(sub.subcategories)) {
        // It's a nested category
        result.push(sub.title)
        sub.subcategories.forEach((nestedSub: string) => {
          result.push(nestedSub)
        })
      }
    })
  }

  return result
}

// Function to map categories to their corresponding pages
export const getCategoryPageMapping = (): Record<string, string> => {
  return {
    // Home, Lawn, and Manual Labor subcategories
    "Lawn & Landscaping": "home-improvement/lawn-garden",
    "Lawn Treatment": "home-improvement/lawn-garden",
    "Landscape Lighting": "home-improvement/lawn-garden",
    "Lawn Mower and Lawn Equipment and Snow Removal Equipment Repair": "home-improvement/lawn-garden",
    "Tree Service": "home-improvement/lawn-garden",
    "Plant Nurseries": "home-improvement/lawn-garden",
    "Mulch Delivery": "home-improvement/lawn-garden",
    "Soil Tilling": "home-improvement/lawn-garden",
    "Leaf Removal": "home-improvement/lawn-garden",
    Hardscaping: "home-improvement/lawn-garden",
    "Snow Removal": "home-improvement/lawn-garden",
    "Other Lawn, Garden and Snow Removal": "home-improvement/lawn-garden",

    // Outside Home Maintenance
    Roofing: "home-improvement/outside-maintenance",
    "Masonry Stone and Brick": "home-improvement/outside-maintenance",
    "Glass Block": "home-improvement/outside-maintenance",
    Siding: "home-improvement/outside-maintenance",
    "Deck Cleaning/Refinishing": "home-improvement/outside-maintenance",
    "Garage Doors": "home-improvement/outside-maintenance",
    "House Painting": "home-improvement/outside-maintenance",
    "Pressure Washing": "home-improvement/outside-maintenance",
    "Foundation Repair": "home-improvement/outside-maintenance",
    "Gutter Cleaning/Repair": "home-improvement/outside-maintenance",
    "Septic Tank Service": "home-improvement/outside-maintenance",
    "Well & Water Pump Repair": "home-improvement/outside-maintenance",
    "Other Outside Home Maintenance and Repair": "home-improvement/outside-maintenance",

    // Outdoor Structures
    "Deck/Patio/Porch Construction": "home-improvement/outdoor-structures",
    "Patio and Patio Enclosures": "home-improvement/outdoor-structures",
    "Exterior Cooking Areas": "home-improvement/outdoor-structures",
    "Awnings/Canopies": "home-improvement/outdoor-structures",
    "Playground Equipment Installation/Basketball Hoops": "home-improvement/outdoor-structures",
    "Fountains and Waterscaping": "home-improvement/outdoor-structures",
    "Pond Construction": "home-improvement/outdoor-structures",
    "Solar Panel Installation": "home-improvement/outdoor-structures",
    "Power Generator Installation": "home-improvement/outdoor-structures",
    "Driveway Gate Installation": "home-improvement/outdoor-structures",
    "Earthquake Retrofitting": "home-improvement/outdoor-structures",
    "Mailbox Installation/Repair": "home-improvement/outdoor-structures",
    Fences: "home-improvement/outdoor-structures",
    "Other Outdoor Structure Assembly/Construction and Fencing": "home-improvement/outdoor-structures",

    // Pool Services
    "Swimming Pool Installers/Builders": "home-improvement/pool-services",
    "Swimming Pool Maintenance/Cleaning": "home-improvement/pool-services",
    "Other Pool Services": "home-improvement/pool-services",

    // Asphalt, Concrete
    "Concrete Driveways": "home-improvement/asphalt-concrete",
    "Asphalt Driveways": "home-improvement/asphalt-concrete",
    "Other Driveways": "home-improvement/asphalt-concrete",
    "Stone & Gravel": "home-improvement/asphalt-concrete",
    "Stamped Concrete": "home-improvement/asphalt-concrete",
    "Concrete Repair": "home-improvement/asphalt-concrete",
    "Other Asphalt, Concrete, Stone and Gravel": "home-improvement/asphalt-concrete",

    // Construction and Design
    "General Contractors": "home-improvement/construction-design",
    Architect: "home-improvement/construction-design",
    "Home Remodeling": "home-improvement/construction-design",
    Demolition: "home-improvement/construction-design",
    "Excavating/Earth Moving": "home-improvement/construction-design",
    "Land Surveyors": "home-improvement/construction-design",
    "Other Home Construction and Design": "home-improvement/construction-design",

    // Inside Home Maintenance
    Electricians: "home-improvement/inside-maintenance",
    Plumbers: "home-improvement/inside-maintenance",
    "Heating, Ventilation, and Air Conditioning Services": "home-improvement/inside-maintenance",
    "Appliance Repair and Installation": "home-improvement/inside-maintenance",
    "Indoor Painting": "home-improvement/inside-maintenance",
    "Drywalling and Repair": "home-improvement/inside-maintenance",
    "Marble & Granite": "home-improvement/inside-maintenance",
    "Water Softeners": "home-improvement/inside-maintenance",
    "Water Heaters": "home-improvement/inside-maintenance",
    Insulation: "home-improvement/inside-maintenance",
    "Air Duct Cleaning": "home-improvement/inside-maintenance",
    "Dryer Duct Cleaning": "home-improvement/inside-maintenance",
    "Central Vacuum Cleaning": "home-improvement/inside-maintenance",
    "Mold Removal": "home-improvement/inside-maintenance",
    "Plaster Work": "home-improvement/inside-maintenance",
    "Water Damage Repair": "home-improvement/inside-maintenance",
    "Basement Waterproofing": "home-improvement/inside-maintenance",
    "Wallpaper Hanging and Removing": "home-improvement/inside-maintenance",
    "Countertop Installation": "home-improvement/inside-maintenance",
    "Ceiling Fan Installation": "home-improvement/inside-maintenance",
    "Bathtub Refinishing": "home-improvement/inside-maintenance",
    "Cabinet Resurfacing": "home-improvement/inside-maintenance",
    "Cabinet Makers": "home-improvement/inside-maintenance",
    "Tile Installation": "home-improvement/inside-maintenance",
    "Other Inside Home Maintenance and Repair": "home-improvement/inside-maintenance",

    // Windows and Doors
    "Window Replacement": "home-improvement/windows-doors",
    "Door Installation": "home-improvement/windows-doors",
    "Window Security Film": "home-improvement/windows-doors",
    "Window Tinting": "home-improvement/windows-doors",
    "Window Dressing/Curtains": "home-improvement/windows-doors",
    "Blind/Drapery Cleaning": "home-improvement/windows-doors",
    Locksmith: "home-improvement/windows-doors",
    "Other Windows and Doors": "home-improvement/windows-doors",

    // Floor/Carpet Care
    "Carpet Installation": "home-improvement/flooring",
    "Hardwood Floor Installation": "home-improvement/flooring",
    "Epoxy Flooring": "home-improvement/flooring",
    "Tile Flooring": "home-improvement/flooring",
    "Laminate Flooring": "home-improvement/flooring",
    "Carpet Cleaning": "home-improvement/flooring",
    "Floor Buffing and Cleaning": "home-improvement/flooring",
    "Oriental Rug Cleaning": "home-improvement/flooring",
    "Other Floor/Carpet Care and Installation": "home-improvement/flooring",

    // Audio/Visual and Security
    "Smart Home Setup": "home-improvement/audio-visual-security",
    "Home Security Solutions": "home-improvement/audio-visual-security",
    "Cinema Room Setup": "home-improvement/audio-visual-security",
    Telecommunication: "home-improvement/audio-visual-security",
    "Cable/Satellite/Antenna Television": "home-improvement/audio-visual-security",
    "Computer Repair": "home-improvement/audio-visual-security",
    "Other Audio/Visual and Home Security": "home-improvement/audio-visual-security",

    // Hazard Mitigation
    "Lead-Based Paint Abatement": "home-improvement/hazard-mitigation",
    "Radon Mitigation": "home-improvement/hazard-mitigation",
    "Asbestos Removal": "home-improvement/hazard-mitigation",
    "Smoke/Carbon Monoxide Detector Installation": "home-improvement/hazard-mitigation",
    "Fire Extinguisher Maintenance": "home-improvement/hazard-mitigation",
    "Other Home Hazard Mitigation": "home-improvement/hazard-mitigation",

    // Pest Control
    "Rodent/ Small Animal Infestations": "home-improvement/pest-control",
    "Wildlife Removal": "home-improvement/pest-control",
    "Insect and Bug Control": "home-improvement/pest-control",
    "Other Pest Control/ Wildlife Removal": "home-improvement/pest-control",

    // Trash Cleanup
    "Biohazard Cleanup": "home-improvement/trash-cleanup",
    "Dumpster Rental": "home-improvement/trash-cleanup",
    "Hauling/Old Furniture and Appliance Removal": "home-improvement/trash-cleanup",
    "Document Shredding": "home-improvement/trash-cleanup",
    "Trash/Junk Removal": "home-improvement/trash-cleanup",
    "Other Trash Cleanup and Removal": "home-improvement/trash-cleanup",

    // Cleaning
    "House Cleaning": "home-improvement/cleaning",
    "Office Cleaning": "home-improvement/cleaning",
    "Window Cleaning": "home-improvement/cleaning",
    "Deep Carpet and Floor Cleaning": "home-improvement/cleaning",
    "Other Home and Office Cleaning": "home-improvement/cleaning",

    // Fireplaces and Chimneys
    "Chimney Sweep": "home-improvement/fireplaces-chimneys",
    "Chimney and Chimney Cap Repair": "home-improvement/fireplaces-chimneys",
    "Gas Fireplace Repair": "home-improvement/fireplaces-chimneys",
    "Fireplace Services": "home-improvement/fireplaces-chimneys",
    "Firewood Suppliers": "home-improvement/fireplaces-chimneys",
    "Heating Oil Suppliers": "home-improvement/fireplaces-chimneys",
    "Other Fireplaces and Chimneys": "home-improvement/fireplaces-chimneys",

    // Movers
    "Moving Truck Rental": "home-improvement/movers",
    "Piano Movers": "home-improvement/movers",
    Movers: "home-improvement/movers",
    "Other Movers/Moving Trucks": "home-improvement/movers",

    // Handymen
    "Odd Jobs and Repairs": "home-improvement/handymen",
    "Product Assembly": "home-improvement/handymen",
    "Other Handymen": "home-improvement/handymen",

    // Retail Stores
    "Supermarkets/ Grocery Stores": "retail-stores",
    "Department Store": "retail-stores",
    "Convenience Store": "retail-stores",
    "Clothing Boutique": "retail-stores",
    "Discount Store": "retail-stores",
    "Warehouse Store": "retail-stores",
    "Electronics Store": "retail-stores",
    Bookstore: "retail-stores",
    "Jewelry Store": "retail-stores",
    "Toy Store": "retail-stores",
    "Sporting Goods Store": "retail-stores",
    "Furniture Store": "retail-stores",
    "Pet Store": "retail-stores",
    "Shoe Store": "retail-stores",
    "Hardware Store": "retail-stores",
    "Stationery Store": "retail-stores",
    "Auto Parts Store": "retail-stores",
    "Health Food Store": "retail-stores",
    "Wine Shop/ Alcohol Sales": "retail-stores",
    "Antique Shop": "retail-stores",
    "Music Store": "retail-stores",
    "Lingerie Store": "retail-stores",
    "Gift Shop": "retail-stores",
    "Butcher Store": "retail-stores",
    "Candy Shop": "retail-stores",
    "Mobile Phone Store": "retail-stores",
    "Optical Store / Eyewear Boutique": "retail-stores",
    Pharmacy: "retail-stores",
    "Home Decor Store": "retail-stores",
    "Party Supply Store": "retail-stores",
    "Garden Center": "retail-stores",
    "Maternity Store": "retail-stores",
    "Cosmetics Store": "retail-stores",
    "Bicycle Shop": "retail-stores",
    "Home Appliance Store": "retail-stores",
    "Cheese Shop": "retail-stores",
    "Craft Store": "retail-stores",
    "Thrift Store": "retail-stores",
    "Handbags Store": "retail-stores",
    "Baby Store": "retail-stores",
    "Tobacco Shop": "retail-stores",
    "Art Supply Store": "retail-stores",

    // Travel and Vacation
    "Tour and Travel Guides": "travel-vacation",
    "Travel Agents": "travel-vacation",
    "Car Rental": "travel-vacation",
    "Boat Rental": "travel-vacation",
    "RV Rental": "travel-vacation",
    "Airpot Pick-up and Drop-off Services": "travel-vacation",
    "Hotels, Motels, and Resorts": "travel-vacation",
    "Bed and Breakfast": "travel-vacation",
    "Air BnB": "travel-vacation",
    "Camp Grounds and Cabins": "travel-vacation",

    // Tailors and Clothing
    "Tailors, Dressmakers, and Custom Sewers": "tailoring-clothing",
    "Laundry and Dry-Cleaning": "tailoring-clothing",
    "Shoe and Leather Repair": "tailoring-clothing",
    "Costume Makers": "tailoring-clothing",
    Upholsterers: "tailoring-clothing",
    "Curtains, Drapes and Window Covering Makers": "tailoring-clothing",

    // Art, Design and Entertainment
    "Fine Artists, Including Painters, Sculptors, and Illustrators": "arts-entertainment",
    "Craft Artists": "arts-entertainment",
    "Musicians and Singers": "arts-entertainment",
    "Recording Studios": "arts-entertainment",
    "Art Galleries": "arts-entertainment",
    "Concert Venues": "arts-entertainment",
    "Fashion Designers": "arts-entertainment",
    "Interior Designers": "arts-entertainment",
    "Photographers and Videographers": "arts-entertainment",
    "Floral Designers": "arts-entertainment",
    "Graphic Designers": "arts-entertainment",
    "All Entertainers and Talent": "arts-entertainment",
    "Talent Agent": "arts-entertainment",
    Modals: "arts-entertainment",

    // Physical Rehabilitation
    "Occupational Therapists": "physical-rehabilitation",
    "Physical Therapists": "physical-rehabilitation",
    "Recreational Therapists": "physical-rehabilitation",
    "Respiratory Therapists": "physical-rehabilitation",
    "Speech-Language Pathologists": "physical-rehabilitation",
    "Exercise Physiologists": "physical-rehabilitation",
    "Massage Therapist": "physical-rehabilitation",
    "Art Therapists": "physical-rehabilitation",
    "Music Therapists": "physical-rehabilitation",
    "Therapists, All Other": "physical-rehabilitation",

    // Finance and Insurance
    Accountants: "financial-services",
    Insurance: "financial-services",
    Advertising: "financial-services",
    Marketing: "financial-services",
    "Financial and Investment Advisers": "financial-services",
    "Debt Consolidators": "financial-services",
    Cryptocurrency: "financial-services",

    // Weddings and Events
    "Event Halls": "weddings-events",
    "Tent and Chair Rentals": "weddings-events",
    "Wedding Planners": "weddings-events",
    "Food Caterers": "weddings-events",
    Bartenders: "weddings-events",
    "Live Music Entertainment": "weddings-events",
    DJs: "weddings-events",
    Performers: "weddings-events",
    "Tuxedo Rentals": "weddings-events",
    "Limousine Services": "weddings-events",
    "Tailors and Seamstresses": "weddings-events",
    "Wedding Dresses": "weddings-events",
    "Wedding Photographers": "weddings-events",
    Florists: "weddings-events",
    "Wedding Cakes": "weddings-events",
    "Marriage Officiants": "weddings-events",
    "Other Weddings and Special Events": "weddings-events",

    // Pet Care
    Veterinarians: "pet-care",
    "Pet Hospitals": "pet-care",
    "Dog Fencing/Invisiable Fence": "pet-care",
    "Pet Groomers": "pet-care",
    "Pet Trainers": "pet-care",
    "Pet Walkers": "pet-care",
    "Pet Sitters": "pet-care",
    "Pet Boarders": "pet-care",
    "Pet Breeders": "pet-care",
    "Pet Shops": "pet-care",
    "Pet Rescues": "pet-care",
    "Aquariums/Pet Enclosures": "pet-care",
    "Pet Poop Pickup": "pet-care",
    "Other Pet Care": "pet-care",

    // Education and Tutoring
    Spanish: "education-tutoring",
    French: "education-tutoring",
    Chinese: "education-tutoring",
    "American Sign Language": "education-tutoring",
    "English as a Second Language": "education-tutoring",
    "Other Language": "education-tutoring",
    "Math - Elementary": "education-tutoring",
    "Math - High School": "education-tutoring",
    "Reading Tutors (Adult and Childeren)": "education-tutoring",
    "Test Prep": "education-tutoring",
    "Other Subjects": "education-tutoring",

    // Real Estate
    "Real Estate Agent": "real-estate",
    "Real Estate Appraising": "real-estate",
    "Home Staging": "real-estate",
    "Home Inspection": "real-estate",
    "Home Energy Audit": "real-estate",
    "Other Home Buying and Selling": "real-estate",

    // Fitness and Athletics
    "Baseball/Softball": "fitness-athletics",
    Golf: "fitness-athletics",
    Tennis: "fitness-athletics",
    Basketball: "fitness-athletics",
    Football: "fitness-athletics",
    Soccer: "fitness-athletics",
    "Ice Skating": "fitness-athletics",
    Gymnastics: "fitness-athletics",
    Pickleball: "fitness-athletics",
    "Table Tennis": "fitness-athletics",
    Dance: "fitness-athletics",
    "Personal Trainers": "fitness-athletics",
    "Group Fitness Classes": "fitness-athletics",
    "Other Athletics, Personal Trainers, etc": "fitness-athletics",
    "Coaches, Scouts, Umpires, Referees": "fitness-athletics",
    "Swim Instruction": "fitness-athletics",

    // Music
    "Piano Lessons": "music-lessons",
    "Guitar Lessons": "music-lessons",
    "Violin Lessons": "music-lessons",
    "Cello Lessons": "music-lessons",
    "Trumpet Lessons": "music-lessons",
    "Other Instrument Lessons": "music-lessons",
    "Instrument Repair": "music-lessons",
    "Used and New Instruments for Sale": "music-lessons",
    "Other Music": "music-lessons",

    // Home Care
    "Non-Medical Elder Care": "care-services",
    "Non-Medical Special Needs Adult Care": "care-services",
    "Babysitting (18+ Sitters only)": "child-care",
    "Other Home Care": "care-services",
    "Childcare Centers": "child-care",
    "Adult Day Services": "elder-care",
    "Rehab/Nursing/Respite and Memory Care": "elder-care",

    // Automotive
    "General Auto Repair": "automotive-services",
    "Engine and Transmission": "automotive-services",
    "Body Shop": "automotive-services",
    "Tire and Brakes": "automotive-services",
    Mufflers: "automotive-services",
    "Oil Change": "automotive-services",
    "Windshield Repair": "automotive-services",
    "Custom Paint": "automotive-services",
    "Detailing Services": "automotive-services",
    "Car Wash": "automotive-services",
    "Auto Parts": "automotive-services",
    "ATV/Motorcycle Repair": "automotive-services",
    "Utility Vehicle Repair": "automotive-services",
    "RV Maintenance and Repair": "automotive-services",
    "Other Automotive/Motorcycle/RV, etc": "automotive-services",
    "Automotive Sales": "automotive-services",
    "Motor Sport/Utility Vehicle/RV Sales": "automotive-services",

    // Beauty and Wellness
    Barbers: "beauty-wellness",
    "Hairdressers, Hairstylists, and Cosmetologists": "beauty-wellness",
    "Manicurists and Pedicurists": "beauty-wellness",
    "Skincare Specialists": "beauty-wellness",
    "Hair Removal": "beauty-wellness",
    "Body Sculpting": "beauty-wellness",
    Spas: "beauty-wellness",
    Tanning: "beauty-wellness",
    "Tattoo and Scar Removal Services": "beauty-wellness",
    "Hair Wigs and Weaves": "beauty-wellness",
    "Beauty Products": "beauty-wellness",
    "Miscellaneous Personal Appearance Workers": "beauty-wellness",

    // Medical Practitioners
    Chiropractors: "medical-practitioners",
    Dentists: "medical-practitioners",
    Orthodontists: "medical-practitioners",
    Optometrists: "medical-practitioners",
    Podiatrists: "medical-practitioners",
    Audiologists: "medical-practitioners",
    "Dietitians and Nutritionists": "medical-practitioners",
    Naturopaths: "medical-practitioners",
    Herbalists: "medical-practitioners",
    Acupuncturist: "medical-practitioners",
    "Orthotists and Prosthetists": "medical-practitioners",
    "Midwives and Doulas": "medical-practitioners",

    // Mental Health
    Counselors: "mental-health",
    "Clinical and Counseling Psychologists": "mental-health",
    "Addiction Specialists": "mental-health",
    "Suboxone, Methadone Clinics": "mental-health",
    "Team Building": "mental-health",
    "Industrial-Organizational Psychologists": "mental-health",
    "Motivational Speakers": "mental-health",

    // Tech and IT
    "Computer Network Specialists": "tech-it-services",
    "Database Administrators": "tech-it-services",
    "Database Architects": "tech-it-services",
    "Computer Programmers": "tech-it-services",
    "Software Developers": "tech-it-services",
    "Website Developers": "tech-it-services",
    "Computer Security": "tech-it-services",
    "BlockChain and Crypto": "tech-it-services",
    "Technology Consultants": "tech-it-services",

    // Food and Dining
    Asian: "food-dining",
    Indian: "food-dining",
    "Middle Eastern": "food-dining",
    Mexican: "food-dining",
    Italian: "food-dining",
    American: "food-dining",
    Greek: "food-dining",
    "Other Ethnic Foods": "food-dining",
    Upscale: "food-dining",
    Casual: "food-dining",
    "Coffee and Tea Shops": "food-dining",
    "Ice Cream, Confectionery and Cakes": "food-dining",
    Pizzeria: "food-dining",
    "Bars/Pubs/Taverns": "food-dining",
    "Organic/Vegan/Vegetarian/Farm to table": "food-dining",
    "Fast Food": "food-dining",
    Catering: "food-dining",
    Buffet: "food-dining",
    "Bakery/Bagels/Donuts": "food-dining",
    Breakfast: "food-dining",
    "24 hour/Open Late": "food-dining",
    "Carts/Stands/Trucks": "food-dining",
    "Dinner Theater": "food-dining",
    "Sandwich Shops": "food-dining",
    "Drive-Ins": "food-dining",
    Seafood: "food-dining",
    "Steak House": "food-dining",
    Sushi: "food-dining",
    Cafeteria: "food-dining",

    // Personal Assistants
    "Personal Drivers": "personal-assistants",
    "Personal Assistants": "personal-assistants",
    Companions: "personal-assistants",
    "Personal Secretaries": "personal-assistants",
    "Personal Shoppers": "personal-assistants",

    // Funeral Services
    "Funeral Homes": "funeral-services",
    Cemetaries: "funeral-services",
    Florists: "funeral-services",
    "Headstones/ Monuments": "funeral-services",
    "Caskets and Urns": "funeral-services",

    // Legal Services
    "Family Lawyer": "legal-services",
    "Criminal Defense Lawyer": "legal-services",
    "Personal Injury Lawyer": "legal-services",
    "Corporate Lawyer": "legal-services",
    "Immigration Lawyer": "legal-services",
    "Intellectual Property Lawyer": "legal-services",
    "Estate Planning Lawyer": "legal-services",
    "Bankruptcy Lawyer": "legal-services",
    "Civil Litigation Lawyer": "legal-services",
    "Real Estate Lawyer": "legal-services",
    "Entertainment Lawyer": "legal-services",
    "Tax Lawyer": "legal-services",
    "Employment Lawyer": "legal-services",
    "Social Security Disability Lawyer": "legal-services",
    "Workers' Compensation Lawyer": "legal-services",
  }
}
